---
title       : "R 기초과정 02"
subtitle    : "집단비교"
author      : "김형준"
job         : "Analytic Director / (주) 퀀트랩 / kim@mindscale.kr "
logo        : logo_03.png
license     : by-nc-sa
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
widgets     : []            # {mathjax, bootstrap, quiz}
mode        : selfcontained
hitheme     : tomorrow      # {tomorrow, tomorrow_night, solarized_dark, solarized_light}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
knit        : slidify::knit2slides

---

## 기초 2 과정

### 학습 목표

데이터 편집하기 
집단 평균 비교하기  
상관관계 이해하기


---  .new-background

## 오늘의 데이터

```{r, echo=F}
par(family="NanumGothic")
setwd("/Users/kimhyungjun/Dropbox/repo/r_basic/html")
df <- read.csv("data/salesC.csv", fileEncoding = "CP949")
```

---  .new-background

```{r}
table(df$성별)
table(df$요일)
table(df$점포)
```

---  .new-background

### 상반기 vs 하반기

```{r}
df.first <- subset(df, 매출월 <= 6 )
mean(df.first$구매건수)
df.latter <- subset(df, 매출월 > 6 )
mean(df.latter$구매건수)
```

---  .new-background

### Histogram

```{r}
hist(df.first$구매건수, xlab = "구매건수", main = "상반기")
```

---  .new-background

### Histogram

```{r}
hist(df.latter$구매건수, xlab = "구매건수", main = "하반기")
```

---  .new-background

```{r}
var.test(df.first$구매건수, df.latter$구매건수)
```

---  .new-background

```{r}
t.test(df.first$구매건수, df.latter$구매건수)
```

---  .new-background

```{r}
df.high <- df[df$구매건수 >= quantile(df$구매건수, probs = .9), ]
mosaicplot(df.high$성별 ~ df.high$요일, 
           main="성별 by 요일", shade=F, 
           color = 1:7, xlab="성별", ylab="요일")
```

---  .new-background

```{r}
mosaicplot(df.high$성별 ~ factor(df.high$요일, levels=c("월", "화", "수", "목", "금", "토", "일")), 
           main="성별 by 요일", shade=F, 
           color = 1:7, xlab="성별", ylab="요일")
```

---  .new-background

```{r}
df.sunday <- subset(df, 요일 ==  "일")
```

```{r}
var.test(구매건수 ~ 성별,  df.sunday)
```

---  .new-background

```{r}
t.test(구매건수 ~ 성별, df.sunday)
```

---  .new-background

```{r}
df.month <- sapply(split(df, df$점포), function(x) x$구매건수)
cor(df.month)
```